# -*- coding: utf-8 -*-
"""Untitled7.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1bp11X-VgMQYfiFKRVjKvEIbVBHpREDPL
"""

from google.colab import files
import pandas as pd
import matplotlib.pyplot as plt
# Subir y cargar dataset de IPASN
uploaded = files.upload()
df_ipasn = pd.read_csv("cs448b_ipasn.csv")

print("\n=== Estadísticas IPASN ===")
print(df_ipasn.describe())

# Gráfica lineal: primera columna numérica
num_cols = df_ipasn.select_dtypes(include="number").columns
if len(num_cols) > 0:
    df_ipasn[num_cols[0]].head(30).plot(kind="line", marker="o")
    plt.title(f"Evolución de {num_cols[0]} (primeros 30 registros)")
    plt.xlabel("Índice")
    plt.ylabel(num_cols[0])
    plt.show()

# Gráfica de barras: primera columna categórica
cat_cols = df_ipasn.select_dtypes(include="object").columns
if len(cat_cols) > 0:
    df_ipasn[cat_cols[0]].value_counts().head(10).plot(kind="bar")
    plt.title(f"Distribución de {cat_cols[0]} (Top 10)")
    plt.xlabel(cat_cols[0])
    plt.ylabel("Cantidad")
    plt.show()