# -*- coding: utf-8 -*-
"""Untitled5.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1t3UzpdtjtV6vnGPsZJ2BNerWv8clmnZZ
"""

from google.colab import files
import pandas as pd
import matplotlib.pyplot as plt

# Subir y cargar dataset de diabetes
uploaded = files.upload()
df_diabetes = pd.read_csv("diabetes.csv")

print("\n=== Estadísticas Diabetes ===")
print(df_diabetes.describe())

# Gráfica lineal: niveles de glucosa en los primeros 30 pacientes
if "Glucose" in df_diabetes.columns:
    df_diabetes["Glucose"].head(30).plot(kind="line", marker="o")
    plt.title("Glucosa en los primeros 30 pacientes")
    plt.xlabel("Paciente")
    plt.ylabel("Glucose")
    plt.show()

# Gráfica de barras: cantidad de pacientes por diagnóstico (Outcome)
if "Outcome" in df_diabetes.columns:
    df_diabetes["Outcome"].value_counts().plot(kind="bar")
    plt.title("Diagnóstico de Diabetes (0=No, 1=Sí)")
    plt.xlabel("Outcome")
    plt.ylabel("Cantidad")
    plt.show()