# -*- coding: utf-8 -*-
"""Grafica Libros

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1zma-jkIvC_5GpeSc3ODXPBJlp7LLig8J
"""

from google.colab import files
import pandas as pd
import matplotlib.pyplot as plt

uploaded = files.upload()
df_books = pd.read_csv("prog_book.csv")

print("\n=== Estadísticas Libros ===")
print(df_books.describe())

# Gráfica lineal: precios de los primeros 30 libros
df_books["Price"].head(30).plot(kind="line", marker="o")
plt.title("Precios de los primeros 30 libros")
plt.xlabel("Libro")
plt.ylabel("Precio")
plt.show()

# Gráfica de barras: cantidad de libros por tipo
if "Type" in df_books.columns:
    df_books["Type"].value_counts().plot(kind="bar")
    plt.title("Cantidad de libros por tipo")
    plt.xlabel("Tipo de libro")
    plt.ylabel("Cantidad")
    plt.show()